In [173]:
import pandas as pd
import numpy as np

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0,0,1,1

In [174]:
predictors = ['season', 'holiday', 'workingday', 'weather', 'temp', 'atemp', 'humidity', 'windspeed']
targets = ["count"]
train.columns
# train.describe()

Index(['datetime', 'season', 'holiday', 'workingday', 'weather', 'temp',
       'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count'],
      dtype='object')

In [175]:
def splitDatetime(data, columndate) :
    datatime= pd.to_datetime(data[columndate])
    data['year'] = datatime.dt.year
    data['month'] = datatime.dt.month
    data['day'] = datatime.dt.day
    data['dayoftheweek'] = datatime.dt.dayofweek
    data['hour'] = datatime.dt.hour
    return data

def harmonize(data):
    data.loc[:,['temp', 'atemp', 'windspeed']]= data.loc[:,['temp', 'atemp', 'windspeed']].round(2)
    return

def normalizedata(data):
    for col in predictors:
        try:
            if data.loc[:, col].mean()>3:
                print(data.loc[:, col].max(), col)
                data.loc[:, col]=(data.loc[:, col]-data.loc[:, col].mean())/data.loc[:, col].std()
        except:
            pass


def RMSLE(predictions, targets):
    return np.sqrt(1/len(predictions)*sum(np.square(np.log(predictions+1)-(np.log(targets+1)))))
    

# train["humspeed"] = train["windspeed"]+train["humidity"]
normalizedata(train)
harmonize(train)
splitDatetime(train, "datetime")
normalizedata(test)
harmonize(test)
splitDatetime(test, "datetime")

# train.describe()
# train.corr(method="kendall")

41.0 temp
45.455 atemp
100 humidity
56.9969 windspeed
40.18 temp
50.0 atemp
100 humidity
55.9986 windspeed

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,year,month,day,dayoftheweek,hour
0,2011-01-20 00:00:00,1,0,1,1,-1.24,-1.44,-0.421140,1.62,2011,1,20,3,0
1,2011-01-20 01:00:00,1,0,1,1,-1.24,-1.18,-0.421140,-1.53,2011,1,20,3,1
2,2011-01-20 02:00:00,1,0,1,1,-1.24,-1.18,-0.421140,-1.53,2011,1,20,3,2
3,2011-01-20 03:00:00,1,0,1,1,-1.24,-1.27,-0.421140,-0.20,2011,1,20,3,3
4,2011-01-20 04:00:00,1,0,1,1,-1.24,-1.27,-0.421140,-0.20,2011,1,20,3,4
5,2011-01-20 05:00:00,1,0,1,1,-1.34,-1.44,-0.213815,0.29,2011,1,20,3,5
6,2011-01-20 06:00:00,1,0,1,1,-1.44,-1.53,-0.213815,0.29,2011,1,20,3,6
7,2011-01-20 07:00:00,1,0,1,1,-1.44,-1.53,-0.472971,0.29,2011,1,20,3,7
8,2011-01-20 08:00:00,1,0,1,1,-1.44,-1.53,-0.472971,0.77,2011,1,20,3,8
9,2011-01-20 09:00:00,1,0,1,2,-1.34,-1.44,-0.628465,0.29,2011,1,20,3,9
10,2011-01-20 10:00:00,1,0,1,1,-1.24,-1.44,-0.835789,0.89,2011,1,20,3,10
11,2011-01-20 11:00:00,1,0,1,2,-1.13,-1.18,-0.991283,-0.20,2011,1,20,3,11
12,2011-01-20 12:00:00,1,0,1,2,-1.03,-0.84,-1.146777,-1.53,2011,1,20,3,12
13,2011-01-20 13:00:00,1,0,1,2,-1.13,-1.10,-0.991283,-0.68,2011,1,20,3,13
14,2011-01-20 14:00:00,1,0,1,2,-1.03,-1.01,-0.991283,-0.44,2011,1,20,3,14
15,2011-01-20 15:00:00,1,0,1,2,-0.93,-0.92,-0.991283,0.04,2011,1,20,3,15
16,2011-01-20 16:00:00,1,0,1,2,-1.03,-1.01,-0.783958,-0.44,2011,1,20,3,16
17,2011-01-20 17:00:00,1,0,1,2,-1.03,-0.92,-0.783958,-0.68,2011,1,20,3,17
18,2011-01-20 18:00:00,1,0,1,2,-1.24,-1.27,-0.421140,0.04,2011,1,20,3,18
19,2011-01-20 19:00:00,1,0,1,1,-1.24,-1.44,-0.421140,1.14,2011,1,20,3,19
20,2011-01-20 20:00:00,1,0,1,2,-1.24,-1.35,-0.213815,0.77,2011,1,20,3,20
21,2011-01-20 21:00:00,1,0,1,2,-1.34,-1.44,-0.213815,0.53,2011,1,20,3,21
22,2011-01-20 22:00:00,1,0,1,2,-1.34,-1.53,0.045341,0.77,2011,1,20,3,22
23,2011-01-20 23:00:00,1,0,1,2,-1.34,-1.53,0.045341,1.14,2011,1,20,3,23
24,2011-01-21 00:00:00,1,0,1,2,-1.34,-1.44,0.304497,0.53,2011,1,21,4,0
25,2011-01-21 01:00:00,1,0,1,2,-1.34,-1.44,0.304497,0.53,2011,1,21,4,1
26,2011-01-21 02:00:00,1,0,1,3,-1.34,-1.35,0.563654,-0.20,2011,1,21,4,2
27,2011-01-21 03:00:00,1,0,1,3,-1.44,-1.53,0.822810,0.89,2011,1,21,4,3
28,2011-01-21 04:00:00,1,0,1,2,-1.44,-1.27,1.185628,-0.80,2011,1,21,4,4
29,2011-01-21 05:00:00,1,0,1,1,-1.34,-1.61,-0.213815,1.86,2011,1,21,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6463,2012-12-30 18:00:00,1,0,0,2,-1.34,-1.53,-1.043114,0.89,2012,12,30,6,18
6464,2012-12-30 19:00:00,1,0,0,1,-0.83,-0.66,-0.161984,-1.53,2012,12,30,6,19
6465,2012-12-30 20:00:00,1,0,0,1,-1.44,-1.61,-0.887621,1.14,2012,12,30,6,20
6466,2012-12-30 21:00:00,1,0,0,1,-1.54,-1.53,-0.680296,-0.20,2012,12,30,6,21
6467,2012-12-30 22:00:00,1,0,0,1,-1.54,-1.61,-0.472971,0.04,2012,12,30,6,22
6468,2012-12-30 23:00:00,1,0,0,1,-1.54,-1.61,-0.680296,0.29,2012,12,30,6,23
6469,2012-12-31 00:00:00,1,0,1,1,-1.64,-1.70,-0.472971,0.04,2012,12,31,0,0
6470,2012-12-31 01:00:00,1,0,1,1,-1.64,-1.70,-0.472971,0.04,2012,12,31,0,1
6471,2012-12-31 02:00:00,1,0,1,1,-1.74,-1.79,-0.265646,-0.20,2012,12,31,0,2
6472,2012-12-31 03:00:00,1,0,1,1,-1.74,-1.70,-0.265646,-0.68,2012,12,31,0,3
6473,2012-12-31 04:00:00,1,0,1,1,-1.85,-1.79,0.252666,-0.68,2012,12,31,0,4
6474,2012-12-31 05:00:00,1,0,1,1,-1.74,-1.87,-0.006490,0.04,2012,12,31,0,5
6475,2012-12-31 06:00:00,1,0,1,1,-1.74,-1.79,-0.006490,-0.20,2012,12,31,0,6
6476,2012-12-31 07:00:00,1,0,1,1,-1.74,-1.70,-0.006490,-0.44,2012,12,31,0,7
6477,2012-12-31 08:00:00,1,0,1,1,-1.85,-1.87,0.252666,-0.44,2012,12,31,0,8
6478,2012-12-31 09:00:00,1,0,1,2,-1.64,-1.53,-0.006490,-0.68,2012,12,31,0,9
6479,2012-12-31 10:00:00,1,0,1,2,-1.54,-1.53,0.252666,-0.44,2012,12,31,0,10
6480,2012-12-31 11:00:00,1,0,1,2,-1.44,-1.44,-0.213815,0.04,2012,12,31,0,11
6481,2012-12-31 12:00:00,1,0,1,2,-1.34,-1.44,-0.421140,0.04,2012,12,31,0,12
6482,2012-12-31 13:00:00,1,0,1,2,-1.24,-1.27,-1.043114,-0.20,2012,12,31,0,13
6483,2012-12-31 14:00:00,1,0,1,2,-1.13,-1.18,-0.991283,0.29,2012,12,31,0,14
6484,2012-12-31 15:00:00,1,0,1,2,-1.13,-1.10,-0.991283,-0.44,2012,12,31,0,15
6485,2012-12-31 16:00:00,1,0,1,2,-1.24,-1.27,-0.835789,0.04,2012,12,31,0,16
6486,2012-12-31 17:00:00,1,0,1,2,-1.24,-1.10,-0.835789,-0.80,2012,12,31,0,17
6487,2012-12-31 18:00:00,1,0,1,2,-1.24,-1.18,-0.835789,-0.44,2012,12,31,0,18
6488,2012-12-31 19:00:00,1,0,1,2,-1.24,-1.27,-0.213815,-0.20,2012,12,31,0,19
6489,2012-12-31 20:00:00,1,0,1,2,-1.24,-1.27,-0.213815,-0.20,2012,12,31,0,20
6490,2012-12-31 21:00:00,1,0,1,1,-1.24,-1.27,-0.213815,-0.20,2012,12,31,0,21
6491,2012-12-31 22:00:00,1,0,1,1,-1.24,-1.18,-0.421140,-0.44,2012,12,31,0,22
6492,2012-12-31 23:00:00,1,0,1,1,-1.24,-1.18,0.045341,-0.44,2012,12,31,0,23

In [176]:
from sklearn import datasets
from sklearn.feature_selection import SelectPercentile, f_classif

train["humspeed"]=train["humidity"]+train["windspeed"]
predictors = ["humspeed", "season", "weather", "holiday", "workingday", "atemp", "humidity", "windspeed" , "dayoftheweek", "hour", "day", "month"]
targets = ["count"]

selector = SelectPercentile(f_classif, percentile=10)
selector.fit(train[predictors], train[targets])

scores = -np.log10(selector.pvalues_)
print(scores)

[  1.66707441e+01   1.98657098e+01   3.64294187e-01   2.91368489e-04
   5.27969361e+00   2.38238551e+02   1.23861391e+02   5.80619585e+00
   2.78320242e+00              inf   2.12400762e-01   1.78985256e+01]

C:\Users\GJ5356\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

# Linear regression

In [177]:
predictors = ["season", "workingday", "holiday", "atemp", "humidity","hour", "year"]
targets = ["count"]

In [178]:
from sklearn.cross_validation import KFold
from sklearn.linear_model import LinearRegression
import numpy as np



trainingdata = pd.concat([train[predictors], train[targets]], axis=1)

kf = KFold(trainingdata.shape[0], n_folds=3, random_state=1)

# Initialize our algorithm class
alg = LinearRegression()

predictions = []
for training, testing in kf:
    print(len(training), len(test))
    # The predictors we're using the train the algorithm.  Note how we only take the rows in the train folds.
    train_predictors = (trainingdata[predictors].iloc[training,:])
    # The target we're using to train the algorithm.
    train_target = trainingdata["count"].iloc[training]
    # Training the algorithm using the predictors and target.
    alg.fit(train_predictors, train_target)
    # We can now make predictions on the test fold
    test_predictions = alg.predict(trainingdata[predictors].iloc[testing,:])
    predictions.append(test_predictions)

predictions = np.concatenate(predictions, axis=0)

#Replacing negative data with mean value
train['predict']=predictions

for x in range(0, 24,1):
    train.loc[(train['predict']<0) & (train['hour']==x), 'predict']=train.loc[(train['predict']>0) & (train['hour']==x), 'predict'].mean()

print(alg.coef_)
print(RMSLE(train['predict'],train['count']))
print(RMSLE(train['count'],train['count']))

7257 6493
7257 6493
7258 6493
[ 19.50722407  -4.63198588 -14.61109745  52.14378007 -29.97172367
   6.23216767  80.89905591]
1.3165289868
0.0

In [197]:

alg = LinearRegression()
alg.fit(train[predictors],  train[targets])

predictions = alg.predict(test[predictors])

print(predictions)
test['predict'] = predictions.flatten()

for x in range(0, 24,1):
    test.loc[(test['predict']<0) & (test['hour']==x), 'predict']=test.loc[(test['predict']>0) & (test['hour']==x), 'predict'].mean()






submission = test[['datetime', 'predict']]
submission.columns=['datetime', 'count']
submission.to_csv("submission.csv", index=False)

# print(test['datetime'])

[[ -30.20389874]
 [  -8.77978687]
 [  -0.97272093]
 ...,
 [ 216.42458318]
 [ 237.56986375]
 [ 225.97153061]]

In [ ]:
from bokeh.io import output_notebook
from bokeh.plotting import figure, show
from bokeh.charts import Scatter
from bokeh.palettes import Spectral4, Spectral6, Spectral8, Spectral11 #color palette

output_notebook()

color_coding = Spectral11

plot2 = figure(width=1000, height=600)
plot2.background_fill_color = "whitesmoke"

#Plot the original load curves of each sites
plot2.xaxis.axis_label= 'Average Week by hour [h]'
plot2.yaxis.axis_label='Average electricity consumption [kWh]'

# xaxis= [x for x in range(0, len(source[1]), 1)]
# plot2.line(train['season'], train[targets] , line_color='blue', line_width=1)
print(train.columns)
p = Scatter(train, x='count', y='predict', color='season')

show(p)